[package]
name = "text_marge"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "1.4.21"

[build-dependencies]
fl2rust = "0.5.19"